### ISSUE TITLE
Self-hosting?

### ISSUE THREAD

**Issue by CarlSinclair** [rikodot/kardi_notes_api#1]
Are those 3 files all that's needed to self-host? Point the web server at one of those `.php` files and that's it? Because the app requires a server URL, and I couldn't find any information on how to get it working neither on the repos nor the website.

**Comment by rikodot** [comment]
There is one or two required actions on your end.

The `notes.sql` contains the required database structure. So if you are using for example phpmyadmin to manage your databases, you simple import this file and it creates everything. Only thing you might need to adjust is the `config` table at the very bottom of this file to match the version of the app (this can be found at the top of the `data_sync.dart` file in the [app source code](https://github.com/rikodot/kardi_notes_app)).
For example at the time of writing [the sql file](https://github.com/rikodot/kardi_notes_api/blob/b9664fa78151160177dcc19cf1e7bc1b22d6b5a9/notes.sql#L182) marks app version 2.0.4 as latest and 2.0.0 as the oldest supported. But [the app](https://github.com/rikodot/kardi_notes_app/blob/da6fa29ccbe65f479d7e040dff06ccbf4532a1de/lib/models/data_sync.dart#L28) is already running version 2.1.0. This is because I do not update the sql file in this repository every time I actually update the app.
As of this moment, you would not even have to change the version in the database, the app would work just fine, but in the future either the app or the api might introduce features that would not be compatible with newer/older versions of each other (in such case I will of course update it in the repository).

Then there is `dh.php` and `handle.php` which you upload to your web server. Right now [handle.php](https://github.com/rikodot/kardi_notes_api/blob/ed179116e2d4a299535e810d34be9e02ec7c30f4/handle.php) imports several other files:
- `error_handler.php` - You do not need this.
- `utils.php` - This is not even used.
- `conn_details.php` & `universal_db_connection.php` - These files are used to implement database connection functionality (the `db_query()` function). You will have to implement this yourself and make sure it connects to you database. The function parameters of course need to match the syntax of its calls. A little programming experience should be enough to get this easily working.

The server url required in the app should point to the `handle.php` file on your web server, for the public api the link would be `https://www.kardi.tech/notes/handle.php`.

It is also good to have a blank `index.php` in the same folder as these files so people will not see which files are contained in the directory. I would also suggest to check every now and then if there are any updates to this repository, just so you are running the latest api version.

If you have any other questions, feel free to re-open the issue. Have a nice day.

**Version 2.1.1 update:**
From this version forward each api version will have its own `.php` file. This is made so new updates will not break old versions of the app.

Only difference for self-hosting setup is that now you have to upload (at least) one more file to the web server (as of this moment only [2.1.1.php](https://github.com/rikodot/kardi_notes_api/blob/118341ca4e30b1fa48c04f27da623b4af7760e29/2.1.1.php) is available). The `handle.php` file no longer holds any actual api functionality, it only selects the correct api version based on each request from the app.

Also I have [updated](https://github.com/rikodot/kardi_notes_api/commit/4f96e36e6a9760e517d0d5c6d8805ba8b1f3822a) the `notes.sql` file. The best way to approach updating your database is watching changes I make to this file and adjusting your database accordingly.
